package de.niklasbednarczyk.nbweather.core.ui.common

import de.niklasbednarczyk.nbweather.core.common.locale.NBCountryType
import de.niklasbednarczyk.nbweather.core.common.string.NBString
import de.niklasbednarczyk.nbweather.core.ui.R
import de.niklasbednarczyk.nbweather.core.ui.image.NBImageItem
import de.niklasbednarczyk.nbweather.core.ui.image.NBImages

val NBCountryType.flag: NBImageItem
    get() = when (this) {
        NBCountryType.AFGHANISTAN -> NBImages.CountryFlagAfghanistan
        NBCountryType.ALAND_ISLANDS -> NBImages.CountryFlagAlandIslands
        NBCountryType.ALBANIA -> NBImages.CountryFlagAlbania
        NBCountryType.ALGERIA -> NBImages.CountryFlagAlgeria
        NBCountryType.AMERICAN_SAMOA -> NBImages.CountryFlagAmericanSamoa
        NBCountryType.ANDORRA -> NBImages.CountryFlagAndorra
        NBCountryType.ANGOLA -> NBImages.CountryFlagAngola
        NBCountryType.ANGUILLA -> NBImages.CountryFlagAnguilla
        NBCountryType.ANTARCTICA -> NBImages.CountryFlagAntarctica
        NBCountryType.ANTIGUA_AND_BARBUDA -> NBImages.CountryFlagAntiguaAndBarbuda
        NBCountryType.ARGENTINA -> NBImages.CountryFlagArgentina
        NBCountryType.ARMENIA -> NBImages.CountryFlagArmenia
        NBCountryType.ARUBA -> NBImages.CountryFlagAruba
        NBCountryType.AUSTRALIA -> NBImages.CountryFlagAustralia
        NBCountryType.AUSTRIA -> NBImages.CountryFlagAustria
        NBCountryType.AZERBAIJAN -> NBImages.CountryFlagAzerbaijan
        NBCountryType.BAHAMAS -> NBImages.CountryFlagBahamas
        NBCountryType.BAHRAIN -> NBImages.CountryFlagBahrain
        NBCountryType.BANGLADESH -> NBImages.CountryFlagBangladesh
        NBCountryType.BARBADOS -> NBImages.CountryFlagBarbados
        NBCountryType.BELARUS -> NBImages.CountryFlagBelarus
        NBCountryType.BELGIUM -> NBImages.CountryFlagBelgium
        NBCountryType.BELIZE -> NBImages.CountryFlagBelize
        NBCountryType.BENIN -> NBImages.CountryFlagBenin
        NBCountryType.BERMUDA -> NBImages.CountryFlagBermuda
        NBCountryType.BHUTAN -> NBImages.CountryFlagBhutan
        NBCountryType.BOLIVIA -> NBImages.CountryFlagBolivia
        NBCountryType.BOSNIA_AND_HERZEGOVINA -> NBImages.CountryFlagBosniaAndHerzegovina
        NBCountryType.BOTSWANA -> NBImages.CountryFlagBotswana
        NBCountryType.BOUVET_ISLAND -> NBImages.CountryFlagBouvetIsland
        NBCountryType.BRAZIL -> NBImages.CountryFlagBrazil
        NBCountryType.BRITISH_INDIAN_OCEAN_TERRITORY -> NBImages.CountryFlagBritishIndianOceanTerritory
        NBCountryType.BRITISH_VIRGIN_ISLANDS -> NBImages.CountryFlagBritishVirginIslands
        NBCountryType.BRUNEI -> NBImages.CountryFlagBrunei
        NBCountryType.BULGARIA -> NBImages.CountryFlagBulgaria
        NBCountryType.BURKINA_FASO -> NBImages.CountryFlagBurkinaFaso
        NBCountryType.BURUNDI -> NBImages.CountryFlagBurundi
        NBCountryType.CAMBODIA -> NBImages.CountryFlagCambodia
        NBCountryType.CAMEROON -> NBImages.CountryFlagCameroon
        NBCountryType.CANADA -> NBImages.CountryFlagCanada
        NBCountryType.CAPE_VERDE -> NBImages.CountryFlagCapeVerde
        NBCountryType.CARIBBEAN_NETHERLANDS -> NBImages.CountryFlagCaribbeanNetherlands
        NBCountryType.CAYMAN_ISLANDS -> NBImages.CountryFlagCaymanIslands
        NBCountryType.CENTRAL_AFRICAN_REPUBLIC -> NBImages.CountryFlagCentralAfricanRepublic
        NBCountryType.CHAD -> NBImages.CountryFlagChad
        NBCountryType.CHILE -> NBImages.CountryFlagChile
        NBCountryType.CHINA -> NBImages.CountryFlagChina
        NBCountryType.CHRISTMAS_ISLAND -> NBImages.CountryFlagChristmasIsland
        NBCountryType.COCOS_KEELING_ISLANDS -> NBImages.CountryFlagCocosKeelingIslands
        NBCountryType.COLOMBIA -> NBImages.CountryFlagColombia
        NBCountryType.COMOROS -> NBImages.CountryFlagComoros
        NBCountryType.COOK_ISLANDS -> NBImages.CountryFlagCookIslands
        NBCountryType.COSTA_RICA -> NBImages.CountryFlagCostaRica
        NBCountryType.CROATIA -> NBImages.CountryFlagCroatia
        NBCountryType.CUBA -> NBImages.CountryFlagCuba
        NBCountryType.CURACAO -> NBImages.CountryFlagCuracao
        NBCountryType.CYPRUS -> NBImages.CountryFlagCyprus
        NBCountryType.CZECHIA -> NBImages.CountryFlagCzechia
        NBCountryType.DENMARK -> NBImages.CountryFlagDenmark
        NBCountryType.DJIBOUTI -> NBImages.CountryFlagDjibouti
        NBCountryType.DOMINICA -> NBImages.CountryFlagDominica
        NBCountryType.DOMINICAN_REPUBLIC -> NBImages.CountryFlagDominicanRepublic
        NBCountryType.DR_CONGO -> NBImages.CountryFlagDrCongo
        NBCountryType.ECUADOR -> NBImages.CountryFlagEcuador
        NBCountryType.EGYPT -> NBImages.CountryFlagEgypt
        NBCountryType.EL_SALVADOR -> NBImages.CountryFlagElSalvador
        NBCountryType.EQUATORIAL_GUINEA -> NBImages.CountryFlagEquatorialGuinea
        NBCountryType.ERITREA -> NBImages.CountryFlagEritrea
        NBCountryType.ESTONIA -> NBImages.CountryFlagEstonia
        NBCountryType.ESWATINI -> NBImages.CountryFlagEswatini
        NBCountryType.ETHIOPIA -> NBImages.CountryFlagEthiopia
        NBCountryType.FALKLAND_ISLANDS -> NBImages.CountryFlagFalklandIslands
        NBCountryType.FAROE_ISLANDS -> NBImages.CountryFlagFaroeIslands
        NBCountryType.FIJI -> NBImages.CountryFlagFiji
        NBCountryType.FINLAND -> NBImages.CountryFlagFinland
        NBCountryType.FRANCE -> NBImages.CountryFlagFrance
        NBCountryType.FRENCH_GUIANA -> NBImages.CountryFlagFrenchGuiana
        NBCountryType.FRENCH_POLYNESIA -> NBImages.CountryFlagFrenchPolynesia
        NBCountryType.FRENCH_SOUTHERN_AND_ANTARCTIC_LANDS -> NBImages.CountryFlagFrenchSouthernAndAntarcticLands
        NBCountryType.GABON -> NBImages.CountryFlagGabon
        NBCountryType.GAMBIA -> NBImages.CountryFlagGambia
        NBCountryType.GEORGIA -> NBImages.CountryFlagGeorgia
        NBCountryType.GERMANY -> NBImages.CountryFlagGermany
        NBCountryType.GHANA -> NBImages.CountryFlagGhana
        NBCountryType.GIBRALTAR -> NBImages.CountryFlagGibraltar
        NBCountryType.GREECE -> NBImages.CountryFlagGreece
        NBCountryType.GREENLAND -> NBImages.CountryFlagGreenland
        NBCountryType.GRENADA -> NBImages.CountryFlagGrenada
        NBCountryType.GUADELOUPE -> NBImages.CountryFlagGuadeloupe
        NBCountryType.GUAM -> NBImages.CountryFlagGuam
        NBCountryType.GUATEMALA -> NBImages.CountryFlagGuatemala
        NBCountryType.GUERNSEY -> NBImages.CountryFlagGuernsey
        NBCountryType.GUINEA -> NBImages.CountryFlagGuinea
        NBCountryType.GUINEA_BISSAU -> NBImages.CountryFlagGuineaBissau
        NBCountryType.GUYANA -> NBImages.CountryFlagGuyana
        NBCountryType.HAITI -> NBImages.CountryFlagHaiti
        NBCountryType.HEARD_ISLAND_AND_MCDONALD_ISLANDS -> NBImages.CountryFlagHeardIslandAndMcdonaldIslands
        NBCountryType.HONDURAS -> NBImages.CountryFlagHonduras
        NBCountryType.HONG_KONG -> NBImages.CountryFlagHongKong
        NBCountryType.HUNGARY -> NBImages.CountryFlagHungary
        NBCountryType.ICELAND -> NBImages.CountryFlagIceland
        NBCountryType.INDIA -> NBImages.CountryFlagIndia
        NBCountryType.INDONESIA -> NBImages.CountryFlagIndonesia
        NBCountryType.IRAN -> NBImages.CountryFlagIran
        NBCountryType.IRAQ -> NBImages.CountryFlagIraq
        NBCountryType.IRELAND -> NBImages.CountryFlagIreland
        NBCountryType.ISLE_OF_MAN -> NBImages.CountryFlagIsleOfMan
        NBCountryType.ISRAEL -> NBImages.CountryFlagIsrael
        NBCountryType.ITALY -> NBImages.CountryFlagItaly
        NBCountryType.IVORY_COAST -> NBImages.CountryFlagIvoryCoast
        NBCountryType.JAMAICA -> NBImages.CountryFlagJamaica
        NBCountryType.JAPAN -> NBImages.CountryFlagJapan
        NBCountryType.JERSEY -> NBImages.CountryFlagJersey
        NBCountryType.JORDAN -> NBImages.CountryFlagJordan
        NBCountryType.KAZAKHSTAN -> NBImages.CountryFlagKazakhstan
        NBCountryType.KENYA -> NBImages.CountryFlagKenya
        NBCountryType.KIRIBATI -> NBImages.CountryFlagKiribati
        NBCountryType.KOSOVO -> NBImages.CountryFlagKosovo
        NBCountryType.KUWAIT -> NBImages.CountryFlagKuwait
        NBCountryType.KYRGYZSTAN -> NBImages.CountryFlagKyrgyzstan
        NBCountryType.LAOS -> NBImages.CountryFlagLaos
        NBCountryType.LATVIA -> NBImages.CountryFlagLatvia
        NBCountryType.LEBANON -> NBImages.CountryFlagLebanon
        NBCountryType.LESOTHO -> NBImages.CountryFlagLesotho
        NBCountryType.LIBERIA -> NBImages.CountryFlagLiberia
        NBCountryType.LIBYA -> NBImages.CountryFlagLibya
        NBCountryType.LIECHTENSTEIN -> NBImages.CountryFlagLiechtenstein
        NBCountryType.LITHUANIA -> NBImages.CountryFlagLithuania
        NBCountryType.LUXEMBOURG -> NBImages.CountryFlagLuxembourg
        NBCountryType.MACAU -> NBImages.CountryFlagMacau
        NBCountryType.MADAGASCAR -> NBImages.CountryFlagMadagascar
        NBCountryType.MALAWI -> NBImages.CountryFlagMalawi
        NBCountryType.MALAYSIA -> NBImages.CountryFlagMalaysia
        NBCountryType.MALDIVES -> NBImages.CountryFlagMaldives
        NBCountryType.MALI -> NBImages.CountryFlagMali
        NBCountryType.MALTA -> NBImages.CountryFlagMalta
        NBCountryType.MARSHALL_ISLANDS -> NBImages.CountryFlagMarshallIslands
        NBCountryType.MARTINIQUE -> NBImages.CountryFlagMartinique
        NBCountryType.MAURITANIA -> NBImages.CountryFlagMauritania
        NBCountryType.MAURITIUS -> NBImages.CountryFlagMauritius
        NBCountryType.MAYOTTE -> NBImages.CountryFlagMayotte
        NBCountryType.MEXICO -> NBImages.CountryFlagMexico
        NBCountryType.MICRONESIA -> NBImages.CountryFlagMicronesia
        NBCountryType.MOLDOVA -> NBImages.CountryFlagMoldova
        NBCountryType.MONACO -> NBImages.CountryFlagMonaco
        NBCountryType.MONGOLIA -> NBImages.CountryFlagMongolia
        NBCountryType.MONTENEGRO -> NBImages.CountryFlagMontenegro
        NBCountryType.MONTSERRAT -> NBImages.CountryFlagMontserrat
        NBCountryType.MOROCCO -> NBImages.CountryFlagMorocco
        NBCountryType.MOZAMBIQUE -> NBImages.CountryFlagMozambique
        NBCountryType.MYANMAR -> NBImages.CountryFlagMyanmar
        NBCountryType.NAMIBIA -> NBImages.CountryFlagNamibia
        NBCountryType.NAURU -> NBImages.CountryFlagNauru
        NBCountryType.NEPAL -> NBImages.CountryFlagNepal
        NBCountryType.NETHERLANDS -> NBImages.CountryFlagNetherlands
        NBCountryType.NEW_CALEDONIA -> NBImages.CountryFlagNewCaledonia
        NBCountryType.NEW_ZEALAND -> NBImages.CountryFlagNewZealand
        NBCountryType.NICARAGUA -> NBImages.CountryFlagNicaragua
        NBCountryType.NIGER -> NBImages.CountryFlagNiger
        NBCountryType.NIGERIA -> NBImages.CountryFlagNigeria
        NBCountryType.NIUE -> NBImages.CountryFlagNiue
        NBCountryType.NORFOLK_ISLAND -> NBImages.CountryFlagNorfolkIsland
        NBCountryType.NORTHERN_MARIANA_ISLANDS -> NBImages.CountryFlagNorthernMarianaIslands
        NBCountryType.NORTH_KOREA -> NBImages.CountryFlagNorthKorea
        NBCountryType.NORTH_MACEDONIA -> NBImages.CountryFlagNorthMacedonia
        NBCountryType.NORWAY -> NBImages.CountryFlagNorway
        NBCountryType.OMAN -> NBImages.CountryFlagOman
        NBCountryType.PAKISTAN -> NBImages.CountryFlagPakistan
        NBCountryType.PALAU -> NBImages.CountryFlagPalau
        NBCountryType.PALESTINE -> NBImages.CountryFlagPalestine
        NBCountryType.PANAMA -> NBImages.CountryFlagPanama
        NBCountryType.PAPUA_NEW_GUINEA -> NBImages.CountryFlagPapuaNewGuinea
        NBCountryType.PARAGUAY -> NBImages.CountryFlagParaguay
        NBCountryType.PERU -> NBImages.CountryFlagPeru
        NBCountryType.PHILIPPINES -> NBImages.CountryFlagPhilippines
        NBCountryType.PITCAIRN_ISLANDS -> NBImages.CountryFlagPitcairnIslands
        NBCountryType.POLAND -> NBImages.CountryFlagPoland
        NBCountryType.PORTUGAL -> NBImages.CountryFlagPortugal
        NBCountryType.PUERTO_RICO -> NBImages.CountryFlagPuertoRico
        NBCountryType.QATAR -> NBImages.CountryFlagQatar
        NBCountryType.REPUBLIC_OF_THE_CONGO -> NBImages.CountryFlagRepublicOfTheCongo
        NBCountryType.REUNION -> NBImages.CountryFlagReunion
        NBCountryType.ROMANIA -> NBImages.CountryFlagRomania
        NBCountryType.RUSSIA -> NBImages.CountryFlagRussia
        NBCountryType.RWANDA -> NBImages.CountryFlagRwanda
        NBCountryType.SAINT_BARTHELEMY -> NBImages.CountryFlagSaintBarthelemy
        NBCountryType.SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA -> NBImages.CountryFlagSaintHelenaAscensionAndTristanDaCunha
        NBCountryType.SAINT_KITTS_AND_NEVIS -> NBImages.CountryFlagSaintKittsAndNevis
        NBCountryType.SAINT_LUCIA -> NBImages.CountryFlagSaintLucia
        NBCountryType.SAINT_MARTIN -> NBImages.CountryFlagSaintMartin
        NBCountryType.SAINT_PIERRE_AND_MIQUELON -> NBImages.CountryFlagSaintPierreAndMiquelon
        NBCountryType.SAINT_VINCENT_AND_THE_GRENADINES -> NBImages.CountryFlagSaintVincentAndTheGrenadines
        NBCountryType.SAMOA -> NBImages.CountryFlagSamoa
        NBCountryType.SAN_MARINO -> NBImages.CountryFlagSanMarino
        NBCountryType.SAO_TOME_AND_PRINCIPE -> NBImages.CountryFlagSaoTomeAndPrincipe
        NBCountryType.SAUDI_ARABIA -> NBImages.CountryFlagSaudiArabia
        NBCountryType.SENEGAL -> NBImages.CountryFlagSenegal
        NBCountryType.SERBIA -> NBImages.CountryFlagSerbia
        NBCountryType.SEYCHELLES -> NBImages.CountryFlagSeychelles
        NBCountryType.SIERRA_LEONE -> NBImages.CountryFlagSierraLeone
        NBCountryType.SINGAPORE -> NBImages.CountryFlagSingapore
        NBCountryType.SINT_MAARTEN -> NBImages.CountryFlagSintMaarten
        NBCountryType.SLOVAKIA -> NBImages.CountryFlagSlovakia
        NBCountryType.SLOVENIA -> NBImages.CountryFlagSlovenia
        NBCountryType.SOLOMON_ISLANDS -> NBImages.CountryFlagSolomonIslands
        NBCountryType.SOMALIA -> NBImages.CountryFlagSomalia
        NBCountryType.SOUTH_AFRICA -> NBImages.CountryFlagSouthAfrica
        NBCountryType.SOUTH_GEORGIA -> NBImages.CountryFlagSouthGeorgia
        NBCountryType.SOUTH_KOREA -> NBImages.CountryFlagSouthKorea
        NBCountryType.SOUTH_SUDAN -> NBImages.CountryFlagSouthSudan
        NBCountryType.SPAIN -> NBImages.CountryFlagSpain
        NBCountryType.SRI_LANKA -> NBImages.CountryFlagSriLanka
        NBCountryType.SUDAN -> NBImages.CountryFlagSudan
        NBCountryType.SURINAME -> NBImages.CountryFlagSuriname
        NBCountryType.SVALBARD_AND_JAN_MAYEN -> NBImages.CountryFlagSvalbardAndJanMayen
        NBCountryType.SWEDEN -> NBImages.CountryFlagSweden
        NBCountryType.SWITZERLAND -> NBImages.CountryFlagSwitzerland
        NBCountryType.SYRIA -> NBImages.CountryFlagSyria
        NBCountryType.TAIWAN -> NBImages.CountryFlagTaiwan
        NBCountryType.TAJIKISTAN -> NBImages.CountryFlagTajikistan
        NBCountryType.TANZANIA -> NBImages.CountryFlagTanzania
        NBCountryType.THAILAND -> NBImages.CountryFlagThailand
        NBCountryType.TIMOR_LESTE -> NBImages.CountryFlagTimorLeste
        NBCountryType.TOGO -> NBImages.CountryFlagTogo
        NBCountryType.TOKELAU -> NBImages.CountryFlagTokelau
        NBCountryType.TONGA -> NBImages.CountryFlagTonga
        NBCountryType.TRINIDAD_AND_TOBAGO -> NBImages.CountryFlagTrinidadAndTobago
        NBCountryType.TUNISIA -> NBImages.CountryFlagTunisia
        NBCountryType.TURKEY -> NBImages.CountryFlagTurkey
        NBCountryType.TURKMENISTAN -> NBImages.CountryFlagTurkmenistan
        NBCountryType.TURKS_AND_CAICOS_ISLANDS -> NBImages.CountryFlagTurksAndCaicosIslands
        NBCountryType.TUVALU -> NBImages.CountryFlagTuvalu
        NBCountryType.UGANDA -> NBImages.CountryFlagUganda
        NBCountryType.UKRAINE -> NBImages.CountryFlagUkraine
        NBCountryType.UNITED_ARAB_EMIRATES -> NBImages.CountryFlagUnitedArabEmirates
        NBCountryType.UNITED_KINGDOM -> NBImages.CountryFlagUnitedKingdom
        NBCountryType.UNITED_STATES -> NBImages.CountryFlagUnitedStates
        NBCountryType.UNITED_STATES_MINOR_OUTLYING_ISLANDS -> NBImages.CountryFlagUnitedStatesMinorOutlyingIslands
        NBCountryType.UNITED_STATES_VIRGIN_ISLANDS -> NBImages.CountryFlagUnitedStatesVirginIslands
        NBCountryType.URUGUAY -> NBImages.CountryFlagUruguay
        NBCountryType.UZBEKISTAN -> NBImages.CountryFlagUzbekistan
        NBCountryType.VANUATU -> NBImages.CountryFlagVanuatu
        NBCountryType.VATICAN_CITY -> NBImages.CountryFlagVaticanCity
        NBCountryType.VENEZUELA -> NBImages.CountryFlagVenezuela
        NBCountryType.VIETNAM -> NBImages.CountryFlagVietnam
        NBCountryType.WALLIS_AND_FUTUNA -> NBImages.CountryFlagWallisAndFutuna
        NBCountryType.WESTERN_SAHARA -> NBImages.CountryFlagWesternSahara
        NBCountryType.YEMEN -> NBImages.CountryFlagYemen
        NBCountryType.ZAMBIA -> NBImages.CountryFlagZambia
        NBCountryType.ZIMBABWE -> NBImages.CountryFlagZimbabwe
    }

val NBCountryType.fullName: NBString
    get() = when (this) {
        NBCountryType.AFGHANISTAN -> NBString.ResString(R.string.common_country_afghanistan)
        NBCountryType.ALAND_ISLANDS -> NBString.ResString(R.string.common_country_aland_islands)
        NBCountryType.ALBANIA -> NBString.ResString(R.string.common_country_albania)
        NBCountryType.ALGERIA -> NBString.ResString(R.string.common_country_algeria)
        NBCountryType.AMERICAN_SAMOA -> NBString.ResString(R.string.common_country_american_samoa)
        NBCountryType.ANDORRA -> NBString.ResString(R.string.common_country_andorra)
        NBCountryType.ANGOLA -> NBString.ResString(R.string.common_country_angola)
        NBCountryType.ANGUILLA -> NBString.ResString(R.string.common_country_anguilla)
        NBCountryType.ANTARCTICA -> NBString.ResString(R.string.common_country_antarctica)
        NBCountryType.ANTIGUA_AND_BARBUDA -> NBString.ResString(R.string.common_country_antigua_and_barbuda)
        NBCountryType.ARGENTINA -> NBString.ResString(R.string.common_country_argentina)
        NBCountryType.ARMENIA -> NBString.ResString(R.string.common_country_armenia)
        NBCountryType.ARUBA -> NBString.ResString(R.string.common_country_aruba)
        NBCountryType.AUSTRALIA -> NBString.ResString(R.string.common_country_australia)
        NBCountryType.AUSTRIA -> NBString.ResString(R.string.common_country_austria)
        NBCountryType.AZERBAIJAN -> NBString.ResString(R.string.common_country_azerbaijan)
        NBCountryType.BAHAMAS -> NBString.ResString(R.string.common_country_bahamas)
        NBCountryType.BAHRAIN -> NBString.ResString(R.string.common_country_bahrain)
        NBCountryType.BANGLADESH -> NBString.ResString(R.string.common_country_bangladesh)
        NBCountryType.BARBADOS -> NBString.ResString(R.string.common_country_barbados)
        NBCountryType.BELARUS -> NBString.ResString(R.string.common_country_belarus)
        NBCountryType.BELGIUM -> NBString.ResString(R.string.common_country_belgium)
        NBCountryType.BELIZE -> NBString.ResString(R.string.common_country_belize)
        NBCountryType.BENIN -> NBString.ResString(R.string.common_country_benin)
        NBCountryType.BERMUDA -> NBString.ResString(R.string.common_country_bermuda)
        NBCountryType.BHUTAN -> NBString.ResString(R.string.common_country_bhutan)
        NBCountryType.BOLIVIA -> NBString.ResString(R.string.common_country_bolivia)
        NBCountryType.BOSNIA_AND_HERZEGOVINA -> NBString.ResString(R.string.common_country_bosnia_and_herzegovina)
        NBCountryType.BOTSWANA -> NBString.ResString(R.string.common_country_botswana)
        NBCountryType.BOUVET_ISLAND -> NBString.ResString(R.string.common_country_bouvet_island)
        NBCountryType.BRAZIL -> NBString.ResString(R.string.common_country_brazil)
        NBCountryType.BRITISH_INDIAN_OCEAN_TERRITORY -> NBString.ResString(R.string.common_country_british_indian_ocean_territory)
        NBCountryType.BRITISH_VIRGIN_ISLANDS -> NBString.ResString(R.string.common_country_british_virgin_islands)
        NBCountryType.BRUNEI -> NBString.ResString(R.string.common_country_brunei)
        NBCountryType.BULGARIA -> NBString.ResString(R.string.common_country_bulgaria)
        NBCountryType.BURKINA_FASO -> NBString.ResString(R.string.common_country_burkina_faso)
        NBCountryType.BURUNDI -> NBString.ResString(R.string.common_country_burundi)
        NBCountryType.CAMBODIA -> NBString.ResString(R.string.common_country_cambodia)
        NBCountryType.CAMEROON -> NBString.ResString(R.string.common_country_cameroon)
        NBCountryType.CANADA -> NBString.ResString(R.string.common_country_canada)
        NBCountryType.CAPE_VERDE -> NBString.ResString(R.string.common_country_cape_verde)
        NBCountryType.CARIBBEAN_NETHERLANDS -> NBString.ResString(R.string.common_country_caribbean_netherlands)
        NBCountryType.CAYMAN_ISLANDS -> NBString.ResString(R.string.common_country_cayman_islands)
        NBCountryType.CENTRAL_AFRICAN_REPUBLIC -> NBString.ResString(R.string.common_country_central_african_republic)
        NBCountryType.CHAD -> NBString.ResString(R.string.common_country_chad)
        NBCountryType.CHILE -> NBString.ResString(R.string.common_country_chile)
        NBCountryType.CHINA -> NBString.ResString(R.string.common_country_china)
        NBCountryType.CHRISTMAS_ISLAND -> NBString.ResString(R.string.common_country_christmas_island)
        NBCountryType.COCOS_KEELING_ISLANDS -> NBString.ResString(R.string.common_country_cocos_keeling_islands)
        NBCountryType.COLOMBIA -> NBString.ResString(R.string.common_country_colombia)
        NBCountryType.COMOROS -> NBString.ResString(R.string.common_country_comoros)
        NBCountryType.COOK_ISLANDS -> NBString.ResString(R.string.common_country_cook_islands)
        NBCountryType.COSTA_RICA -> NBString.ResString(R.string.common_country_costa_rica)
        NBCountryType.CROATIA -> NBString.ResString(R.string.common_country_croatia)
        NBCountryType.CUBA -> NBString.ResString(R.string.common_country_cuba)
        NBCountryType.CURACAO -> NBString.ResString(R.string.common_country_curacao)
        NBCountryType.CYPRUS -> NBString.ResString(R.string.common_country_cyprus)
        NBCountryType.CZECHIA -> NBString.ResString(R.string.common_country_czechia)
        NBCountryType.DENMARK -> NBString.ResString(R.string.common_country_denmark)
        NBCountryType.DJIBOUTI -> NBString.ResString(R.string.common_country_djibouti)
        NBCountryType.DOMINICA -> NBString.ResString(R.string.common_country_dominica)
        NBCountryType.DOMINICAN_REPUBLIC -> NBString.ResString(R.string.common_country_dominican_republic)
        NBCountryType.DR_CONGO -> NBString.ResString(R.string.common_country_dr_congo)
        NBCountryType.ECUADOR -> NBString.ResString(R.string.common_country_ecuador)
        NBCountryType.EGYPT -> NBString.ResString(R.string.common_country_egypt)
        NBCountryType.EL_SALVADOR -> NBString.ResString(R.string.common_country_el_salvador)
        NBCountryType.EQUATORIAL_GUINEA -> NBString.ResString(R.string.common_country_equatorial_guinea)
        NBCountryType.ERITREA -> NBString.ResString(R.string.common_country_eritrea)
        NBCountryType.ESTONIA -> NBString.ResString(R.string.common_country_estonia)
        NBCountryType.ESWATINI -> NBString.ResString(R.string.common_country_eswatini)
        NBCountryType.ETHIOPIA -> NBString.ResString(R.string.common_country_ethiopia)
        NBCountryType.FALKLAND_ISLANDS -> NBString.ResString(R.string.common_country_falkland_islands)
        NBCountryType.FAROE_ISLANDS -> NBString.ResString(R.string.common_country_faroe_islands)
        NBCountryType.FIJI -> NBString.ResString(R.string.common_country_fiji)
        NBCountryType.FINLAND -> NBString.ResString(R.string.common_country_finland)
        NBCountryType.FRANCE -> NBString.ResString(R.string.common_country_france)
        NBCountryType.FRENCH_GUIANA -> NBString.ResString(R.string.common_country_french_guiana)
        NBCountryType.FRENCH_POLYNESIA -> NBString.ResString(R.string.common_country_french_polynesia)
        NBCountryType.FRENCH_SOUTHERN_AND_ANTARCTIC_LANDS -> NBString.ResString(R.string.common_country_french_southern_and_antarctic_lands)
        NBCountryType.GABON -> NBString.ResString(R.string.common_country_gabon)
        NBCountryType.GAMBIA -> NBString.ResString(R.string.common_country_gambia)
        NBCountryType.GEORGIA -> NBString.ResString(R.string.common_country_georgia)
        NBCountryType.GERMANY -> NBString.ResString(R.string.common_country_germany)
        NBCountryType.GHANA -> NBString.ResString(R.string.common_country_ghana)
        NBCountryType.GIBRALTAR -> NBString.ResString(R.string.common_country_gibraltar)
        NBCountryType.GREECE -> NBString.ResString(R.string.common_country_greece)
        NBCountryType.GREENLAND -> NBString.ResString(R.string.common_country_greenland)
        NBCountryType.GRENADA -> NBString.ResString(R.string.common_country_grenada)
        NBCountryType.GUADELOUPE -> NBString.ResString(R.string.common_country_guadeloupe)
        NBCountryType.GUAM -> NBString.ResString(R.string.common_country_guam)
        NBCountryType.GUATEMALA -> NBString.ResString(R.string.common_country_guatemala)
        NBCountryType.GUERNSEY -> NBString.ResString(R.string.common_country_guernsey)
        NBCountryType.GUINEA -> NBString.ResString(R.string.common_country_guinea)
        NBCountryType.GUINEA_BISSAU -> NBString.ResString(R.string.common_country_guinea_bissau)
        NBCountryType.GUYANA -> NBString.ResString(R.string.common_country_guyana)
        NBCountryType.HAITI -> NBString.ResString(R.string.common_country_haiti)
        NBCountryType.HEARD_ISLAND_AND_MCDONALD_ISLANDS -> NBString.ResString(R.string.common_country_heard_island_and_mcdonald_islands)
        NBCountryType.HONDURAS -> NBString.ResString(R.string.common_country_honduras)
        NBCountryType.HONG_KONG -> NBString.ResString(R.string.common_country_hong_kong)
        NBCountryType.HUNGARY -> NBString.ResString(R.string.common_country_hungary)
        NBCountryType.ICELAND -> NBString.ResString(R.string.common_country_iceland)
        NBCountryType.INDIA -> NBString.ResString(R.string.common_country_india)
        NBCountryType.INDONESIA -> NBString.ResString(R.string.common_country_indonesia)
        NBCountryType.IRAN -> NBString.ResString(R.string.common_country_iran)
        NBCountryType.IRAQ -> NBString.ResString(R.string.common_country_iraq)
        NBCountryType.IRELAND -> NBString.ResString(R.string.common_country_ireland)
        NBCountryType.ISLE_OF_MAN -> NBString.ResString(R.string.common_country_isle_of_man)
        NBCountryType.ISRAEL -> NBString.ResString(R.string.common_country_israel)
        NBCountryType.ITALY -> NBString.ResString(R.string.common_country_italy)
        NBCountryType.IVORY_COAST -> NBString.ResString(R.string.common_country_ivory_coast)
        NBCountryType.JAMAICA -> NBString.ResString(R.string.common_country_jamaica)
        NBCountryType.JAPAN -> NBString.ResString(R.string.common_country_japan)
        NBCountryType.JERSEY -> NBString.ResString(R.string.common_country_jersey)
        NBCountryType.JORDAN -> NBString.ResString(R.string.common_country_jordan)
        NBCountryType.KAZAKHSTAN -> NBString.ResString(R.string.common_country_kazakhstan)
        NBCountryType.KENYA -> NBString.ResString(R.string.common_country_kenya)
        NBCountryType.KIRIBATI -> NBString.ResString(R.string.common_country_kiribati)
        NBCountryType.KOSOVO -> NBString.ResString(R.string.common_country_kosovo)
        NBCountryType.KUWAIT -> NBString.ResString(R.string.common_country_kuwait)
        NBCountryType.KYRGYZSTAN -> NBString.ResString(R.string.common_country_kyrgyzstan)
        NBCountryType.LAOS -> NBString.ResString(R.string.common_country_laos)
        NBCountryType.LATVIA -> NBString.ResString(R.string.common_country_latvia)
        NBCountryType.LEBANON -> NBString.ResString(R.string.common_country_lebanon)
        NBCountryType.LESOTHO -> NBString.ResString(R.string.common_country_lesotho)
        NBCountryType.LIBERIA -> NBString.ResString(R.string.common_country_liberia)
        NBCountryType.LIBYA -> NBString.ResString(R.string.common_country_libya)
        NBCountryType.LIECHTENSTEIN -> NBString.ResString(R.string.common_country_liechtenstein)
        NBCountryType.LITHUANIA -> NBString.ResString(R.string.common_country_lithuania)
        NBCountryType.LUXEMBOURG -> NBString.ResString(R.string.common_country_luxembourg)
        NBCountryType.MACAU -> NBString.ResString(R.string.common_country_macau)
        NBCountryType.MADAGASCAR -> NBString.ResString(R.string.common_country_madagascar)
        NBCountryType.MALAWI -> NBString.ResString(R.string.common_country_malawi)
        NBCountryType.MALAYSIA -> NBString.ResString(R.string.common_country_malaysia)
        NBCountryType.MALDIVES -> NBString.ResString(R.string.common_country_maldives)
        NBCountryType.MALI -> NBString.ResString(R.string.common_country_mali)
        NBCountryType.MALTA -> NBString.ResString(R.string.common_country_malta)
        NBCountryType.MARSHALL_ISLANDS -> NBString.ResString(R.string.common_country_marshall_islands)
        NBCountryType.MARTINIQUE -> NBString.ResString(R.string.common_country_martinique)
        NBCountryType.MAURITANIA -> NBString.ResString(R.string.common_country_mauritania)
        NBCountryType.MAURITIUS -> NBString.ResString(R.string.common_country_mauritius)
        NBCountryType.MAYOTTE -> NBString.ResString(R.string.common_country_mayotte)
        NBCountryType.MEXICO -> NBString.ResString(R.string.common_country_mexico)
        NBCountryType.MICRONESIA -> NBString.ResString(R.string.common_country_micronesia)
        NBCountryType.MOLDOVA -> NBString.ResString(R.string.common_country_moldova)
        NBCountryType.MONACO -> NBString.ResString(R.string.common_country_monaco)
        NBCountryType.MONGOLIA -> NBString.ResString(R.string.common_country_mongolia)
        NBCountryType.MONTENEGRO -> NBString.ResString(R.string.common_country_montenegro)
        NBCountryType.MONTSERRAT -> NBString.ResString(R.string.common_country_montserrat)
        NBCountryType.MOROCCO -> NBString.ResString(R.string.common_country_morocco)
        NBCountryType.MOZAMBIQUE -> NBString.ResString(R.string.common_country_mozambique)
        NBCountryType.MYANMAR -> NBString.ResString(R.string.common_country_myanmar)
        NBCountryType.NAMIBIA -> NBString.ResString(R.string.common_country_namibia)
        NBCountryType.NAURU -> NBString.ResString(R.string.common_country_nauru)
        NBCountryType.NEPAL -> NBString.ResString(R.string.common_country_nepal)
        NBCountryType.NETHERLANDS -> NBString.ResString(R.string.common_country_netherlands)
        NBCountryType.NEW_CALEDONIA -> NBString.ResString(R.string.common_country_new_caledonia)
        NBCountryType.NEW_ZEALAND -> NBString.ResString(R.string.common_country_new_zealand)
        NBCountryType.NICARAGUA -> NBString.ResString(R.string.common_country_nicaragua)
        NBCountryType.NIGER -> NBString.ResString(R.string.common_country_niger)
        NBCountryType.NIGERIA -> NBString.ResString(R.string.common_country_nigeria)
        NBCountryType.NIUE -> NBString.ResString(R.string.common_country_niue)
        NBCountryType.NORFOLK_ISLAND -> NBString.ResString(R.string.common_country_norfolk_island)
        NBCountryType.NORTHERN_MARIANA_ISLANDS -> NBString.ResString(R.string.common_country_northern_mariana_islands)
        NBCountryType.NORTH_KOREA -> NBString.ResString(R.string.common_country_north_korea)
        NBCountryType.NORTH_MACEDONIA -> NBString.ResString(R.string.common_country_north_macedonia)
        NBCountryType.NORWAY -> NBString.ResString(R.string.common_country_norway)
        NBCountryType.OMAN -> NBString.ResString(R.string.common_country_oman)
        NBCountryType.PAKISTAN -> NBString.ResString(R.string.common_country_pakistan)
        NBCountryType.PALAU -> NBString.ResString(R.string.common_country_palau)
        NBCountryType.PALESTINE -> NBString.ResString(R.string.common_country_palestine)
        NBCountryType.PANAMA -> NBString.ResString(R.string.common_country_panama)
        NBCountryType.PAPUA_NEW_GUINEA -> NBString.ResString(R.string.common_country_papua_new_guinea)
        NBCountryType.PARAGUAY -> NBString.ResString(R.string.common_country_paraguay)
        NBCountryType.PERU -> NBString.ResString(R.string.common_country_peru)
        NBCountryType.PHILIPPINES -> NBString.ResString(R.string.common_country_philippines)
        NBCountryType.PITCAIRN_ISLANDS -> NBString.ResString(R.string.common_country_pitcairn_islands)
        NBCountryType.POLAND -> NBString.ResString(R.string.common_country_poland)
        NBCountryType.PORTUGAL -> NBString.ResString(R.string.common_country_portugal)
        NBCountryType.PUERTO_RICO -> NBString.ResString(R.string.common_country_puerto_rico)
        NBCountryType.QATAR -> NBString.ResString(R.string.common_country_qatar)
        NBCountryType.REPUBLIC_OF_THE_CONGO -> NBString.ResString(R.string.common_country_republic_of_the_congo)
        NBCountryType.REUNION -> NBString.ResString(R.string.common_country_reunion)
        NBCountryType.ROMANIA -> NBString.ResString(R.string.common_country_romania)
        NBCountryType.RUSSIA -> NBString.ResString(R.string.common_country_russia)
        NBCountryType.RWANDA -> NBString.ResString(R.string.common_country_rwanda)
        NBCountryType.SAINT_BARTHELEMY -> NBString.ResString(R.string.common_country_saint_barthelemy)
        NBCountryType.SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA -> NBString.ResString(R.string.common_country_saint_helena_ascension_and_tristan_da_cunha)
        NBCountryType.SAINT_KITTS_AND_NEVIS -> NBString.ResString(R.string.common_country_saint_kitts_and_nevis)
        NBCountryType.SAINT_LUCIA -> NBString.ResString(R.string.common_country_saint_lucia)
        NBCountryType.SAINT_MARTIN -> NBString.ResString(R.string.common_country_saint_martin)
        NBCountryType.SAINT_PIERRE_AND_MIQUELON -> NBString.ResString(R.string.common_country_saint_pierre_and_miquelon)
        NBCountryType.SAINT_VINCENT_AND_THE_GRENADINES -> NBString.ResString(R.string.common_country_saint_vincent_and_the_grenadines)
        NBCountryType.SAMOA -> NBString.ResString(R.string.common_country_samoa)
        NBCountryType.SAN_MARINO -> NBString.ResString(R.string.common_country_san_marino)
        NBCountryType.SAO_TOME_AND_PRINCIPE -> NBString.ResString(R.string.common_country_sao_tome_and_principe)
        NBCountryType.SAUDI_ARABIA -> NBString.ResString(R.string.common_country_saudi_arabia)
        NBCountryType.SENEGAL -> NBString.ResString(R.string.common_country_senegal)
        NBCountryType.SERBIA -> NBString.ResString(R.string.common_country_serbia)
        NBCountryType.SEYCHELLES -> NBString.ResString(R.string.common_country_seychelles)
        NBCountryType.SIERRA_LEONE -> NBString.ResString(R.string.common_country_sierra_leone)
        NBCountryType.SINGAPORE -> NBString.ResString(R.string.common_country_singapore)
        NBCountryType.SINT_MAARTEN -> NBString.ResString(R.string.common_country_sint_maarten)
        NBCountryType.SLOVAKIA -> NBString.ResString(R.string.common_country_slovakia)
        NBCountryType.SLOVENIA -> NBString.ResString(R.string.common_country_slovenia)
        NBCountryType.SOLOMON_ISLANDS -> NBString.ResString(R.string.common_country_solomon_islands)
        NBCountryType.SOMALIA -> NBString.ResString(R.string.common_country_somalia)
        NBCountryType.SOUTH_AFRICA -> NBString.ResString(R.string.common_country_south_africa)
        NBCountryType.SOUTH_GEORGIA -> NBString.ResString(R.string.common_country_south_georgia)
        NBCountryType.SOUTH_KOREA -> NBString.ResString(R.string.common_country_south_korea)
        NBCountryType.SOUTH_SUDAN -> NBString.ResString(R.string.common_country_south_sudan)
        NBCountryType.SPAIN -> NBString.ResString(R.string.common_country_spain)
        NBCountryType.SRI_LANKA -> NBString.ResString(R.string.common_country_sri_lanka)
        NBCountryType.SUDAN -> NBString.ResString(R.string.common_country_sudan)
        NBCountryType.SURINAME -> NBString.ResString(R.string.common_country_suriname)
        NBCountryType.SVALBARD_AND_JAN_MAYEN -> NBString.ResString(R.string.common_country_svalbard_and_jan_mayen)
        NBCountryType.SWEDEN -> NBString.ResString(R.string.common_country_sweden)
        NBCountryType.SWITZERLAND -> NBString.ResString(R.string.common_country_switzerland)
        NBCountryType.SYRIA -> NBString.ResString(R.string.common_country_syria)
        NBCountryType.TAIWAN -> NBString.ResString(R.string.common_country_taiwan)
        NBCountryType.TAJIKISTAN -> NBString.ResString(R.string.common_country_tajikistan)
        NBCountryType.TANZANIA -> NBString.ResString(R.string.common_country_tanzania)
        NBCountryType.THAILAND -> NBString.ResString(R.string.common_country_thailand)
        NBCountryType.TIMOR_LESTE -> NBString.ResString(R.string.common_country_timor_leste)
        NBCountryType.TOGO -> NBString.ResString(R.string.common_country_togo)
        NBCountryType.TOKELAU -> NBString.ResString(R.string.common_country_tokelau)
        NBCountryType.TONGA -> NBString.ResString(R.string.common_country_tonga)
        NBCountryType.TRINIDAD_AND_TOBAGO -> NBString.ResString(R.string.common_country_trinidad_and_tobago)
        NBCountryType.TUNISIA -> NBString.ResString(R.string.common_country_tunisia)
        NBCountryType.TURKEY -> NBString.ResString(R.string.common_country_turkey)
        NBCountryType.TURKMENISTAN -> NBString.ResString(R.string.common_country_turkmenistan)
        NBCountryType.TURKS_AND_CAICOS_ISLANDS -> NBString.ResString(R.string.common_country_turks_and_caicos_islands)
        NBCountryType.TUVALU -> NBString.ResString(R.string.common_country_tuvalu)
        NBCountryType.UGANDA -> NBString.ResString(R.string.common_country_uganda)
        NBCountryType.UKRAINE -> NBString.ResString(R.string.common_country_ukraine)
        NBCountryType.UNITED_ARAB_EMIRATES -> NBString.ResString(R.string.common_country_united_arab_emirates)
        NBCountryType.UNITED_KINGDOM -> NBString.ResString(R.string.common_country_united_kingdom)
        NBCountryType.UNITED_STATES -> NBString.ResString(R.string.common_country_united_states)
        NBCountryType.UNITED_STATES_MINOR_OUTLYING_ISLANDS -> NBString.ResString(R.string.common_country_united_states_minor_outlying_islands)
        NBCountryType.UNITED_STATES_VIRGIN_ISLANDS -> NBString.ResString(R.string.common_country_united_states_virgin_islands)
        NBCountryType.URUGUAY -> NBString.ResString(R.string.common_country_uruguay)
        NBCountryType.UZBEKISTAN -> NBString.ResString(R.string.common_country_uzbekistan)
        NBCountryType.VANUATU -> NBString.ResString(R.string.common_country_vanuatu)
        NBCountryType.VATICAN_CITY -> NBString.ResString(R.string.common_country_vatican_city)
        NBCountryType.VENEZUELA -> NBString.ResString(R.string.common_country_venezuela)
        NBCountryType.VIETNAM -> NBString.ResString(R.string.common_country_vietnam)
        NBCountryType.WALLIS_AND_FUTUNA -> NBString.ResString(R.string.common_country_wallis_and_futuna)
        NBCountryType.WESTERN_SAHARA -> NBString.ResString(R.string.common_country_western_sahara)
        NBCountryType.YEMEN -> NBString.ResString(R.string.common_country_yemen)
        NBCountryType.ZAMBIA -> NBString.ResString(R.string.common_country_zambia)
        NBCountryType.ZIMBABWE -> NBString.ResString(R.string.common_country_zimbabwe)
    }